### Testando o Health Check (Nuvem)
GET https://api-groove-bot-enzo-dxckg0brada4gng7.centralus-01.azurewebsites.net/

### Testando o Agente LangGraph (Nuvem)
POST https://api-groove-bot-enzo-dxckg0brada4gng7.centralus-01.azurewebsites.net/chat
Content-Type: application/json

{
  "pergunta": "Qual disco do genêro Sertanejo posso comprar com R$ 50,00?"
}