name: Pipeline MLOps - Groove Bot

# 1. Quando este robô deve trabalhar?
on:
  push:
    branches:
      - main # Roda sempre que você enviar código novo para a branch principal

jobs:
  testes-automatizados:
    name: Rodar Avaliação do Agente RAG
    runs-on: ubuntu-latest # O GitHub vai criar um "computador" Linux temporário

    steps:
      # Passo A: O robô faz o download do seu código
      - name: 📥 Baixar o código do repositório
        uses: actions/checkout@v4

      # Passo B: O robô instala o Python 3.12
      - name: 🐍 Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # Deixa a instalação mais rápida

      # Passo C: O robô instala suas bibliotecas
      - name: 📦 Instalar Dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Passo D: O robô roda os testes do MLflow!
      - name: 🧪 Executar Testes de Acurácia (Baseline > 80%)
        env:
          # O robô vai pegar as senhas dos "Segredos" do GitHub, e não do seu .env
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          AZURE_LLM_KEY: ${{ secrets.AZURE_LLM_KEY }}
          AZURE_LLM_ENDPOINT: ${{ secrets.AZURE_LLM_ENDPOINT }}
          AZURE_OPENAI_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          AZURE_LLM_JUDGE_KEY: ${{ secrets.AZURE_LLM_JUDGE_KEY }}
          AZURE_LLM_JUDGE_ENDPOINT: ${{ secrets.AZURE_LLM_JUDGE_ENDPOINT }}
          AZURE_OPENAI_DEPLOYMENT_NAME_JUDGE: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME_JUDGE }}
        run: |
          export PYTHONPATH=.
          python test/NOME_DO_SEU_ARQUIVO.py